import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from mysqlboilerplate import run_query
df_genres=run_query("SELECT genre, COUNT(*) AS genre_count FROM generes GROUP BY genre ORDER BY genre_count DESC LIMIT 10")
print(df_genres)
genres=pd.DataFrame(df_genres,columns=["genre","genre_count"])
plt.figure(figsize=(10,6))
sns.barplot(x="genre_count",y="genre",data=genres,hue="genre",palette="viridis")
plt.title("top 10 movie genres",fontsize=16)
plt.xlabel("number of movies")
plt.ylabel("genre")
plt.tight_layout()
plt.savefig("top_genres.png")

df_actors=run_query("SELECT actor_name, COUNT(*)AS appearances FROM actors GROUP BY actor_name ORDER BY appearances DESC LIMIT 10")
print(df_actors)
actors=pd.DataFrame(df_actors,columns=["actor_name","appearances"])
plt.figure(figsize=(10,6))
sns.barplot(x="appearances",y="actor_name",data=actors,hue="actor_name",palette="coolwarm")
plt.title("top 10 actors by frequency",fontsize=16)
plt.xlabel("number of movies")
plt.ylabel("actor")
plt.tight_layout()
plt.savefig("top_actors.png")

df_movies=run_query("""SELECT title,release_year,rating FROM movies WHERE rating>8.0 AND release_year>2010 ORDER BY rating DESC""")
print(df_movies)
rating_df=run_query("""SELECT rating FROM movies WHERE rating IS NOT NULL""")
print(rating_df)
rating=pd.DataFrame(rating_df,columns=["rating"])
plt.figure(figsize=(8,6))
sns.histplot(rating["rating"], bins=20, kde=True, color="skyblue")
plt.title("Distribution of Movie Ratings", fontsize=16)
plt.xlabel("Rating")
plt.ylabel("Count")
plt.tight_layout()
plt.savefig("rating_distribution.png")
plt.show()
